# Site
site_name: Securing Microsoft 365
site_url: https://www.securingm365.com/
site_author: Anthony Porter
site_description: Securing Microsoft 365
edit_uri: tree/main/docs

# Repository
repo_name: AntoPorter
repo_url: https://github.com/AntoPorter/antoporter.github.io

# Themes
theme:
 name: material
 custom_dir: material/overrides
 features:
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.action.view
    - content.tooltips
 language: en
 favicon: images/favicon.png
 logo: images/logo.png
 icon:
   repo: fontawesome/brands/git-alt

# Plugins
 plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - macros
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: date
  - social:
      cards_layout: default

# Colour Schemes
 palette:
  - scheme: slate
    toggle:
     icon: material/toggle-switch-off-outline
     name: Switch to light mode
    primary: teal
    accent: deep purple
  - scheme: default
    toggle:
     icon: material/toggle-switch
     name: Switch to dark mode
    primary: teal
    accent: deep purple
 font:
    text: Roboto
    code: Roboto Mono

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/AntoPorter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/anthonyantoporter/

  analytics:
    provider: google
    property: G-2H6Z23PMCP

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Copyright
copyright: |
  &copy; 2024 <a href="https://github.com/AntoPorter"  target="_blank" rel="noopener">Anthony Porter</a>

# Navigation
nav:
  - Homepage:
    - index.md
    - Microsoft Defender XDR: defenderxdr/index.md
    - Endpoint Management: endpoint/index.md
    - Microsoft Purview: purview/index.md
    - Microsoft Copilot: copilot/index.md
    - Microsoft Entra: entra/index.md
    - Miscellaneous: misc/index.md
    - Out of Band Podcast: podcast/outofband/index.md
    - About Me: aboutme.md
  - Microsoft Defender XDR:
    - Microsoft Defender XDR: defenderxdr/index.md
    - Microsoft Defender for Endpoint:
      - defenderxdr/defenderendpoint/enforcementscope.md
    - Microsoft Defender for Office 365:
      - defenderxdr/defenderoffice365/ll-safelinks-rewrap.md
    - Microsoft Defender for Identity:
      - defenderxdr/defenderidentity/top5features.md  
    - Microsoft Defender for Cloud Apps:
      - defenderxdr/defendercloudapps/demystifying-policies.md
      - defenderxdr/defendercloudapps/appblocking-dfe.md
      - defenderxdr/defendercloudapps/unsanctioning-riskyapps.md
    - Microsoft Sentinel:
      - defenderxdr/sentinel/unifiedsoc.md
      - defenderxdr/sentinel/soar.md
      - defenderxdr/sentinel/workspaceworkbookexport.md
  - Endpoint Management: 
    - Endpoint Management: endpoint/index.md
    - Microsoft Intune:
      - endpoint/intune/quickwins-securitytasks.md
      - endpoint/intune/quickwins-appcontrolforbusiness.md
      - endpoint/intune/quickwins-laps.md
      - endpoint/intune/quickwins-securitybaselines.md
      - endpoint/intune/quickwins-applications.md
      - endpoint/intune/quickwins-autopatch.md
      - endpoint/intune/quickwins-grouppolicyanalytics.md
      - endpoint/intune/remediations.md
      - endpoint/intune/bitlocker_selfservice.md
      - endpoint/intune/baselineinsights.md
    - Microsoft Configuration Manager:
      - endpoint/configmgr/challengesolution-mcmtointune.md
  - Microsoft Purview: 
    - purview/index.md
    - purview/browsersignaldetection.md
    - purview/m365copilotDLP.md
  - Microsoft Copilot:
    - Microsoft Copilot: copilot/index.md
    - Microsoft Security Copilot:
      - copilot/copilotsecurity/globalaibootcamppresentation.md
      - copilot/copilotsecurity/deploy-templatespec.md
      - copilot/copilotsecurity/logicapp-promptbook.md
      - copilot/copilotsecurity/promptinspiration.md
      - copilot/copilotsecurity/ll-scudeployment.md
    - Microsoft 365 Copilot:
      - copilot/copilotm365/gettingstarted.md
      - copilot/copilotm365/enablecopilotm365.md
  - Microsoft Entra:
    - entra/index.md
    - entra/azconnect-device.md
    - entra/exploringtrv2.md
  - Miscellaneous:
    - misc/index.md
    - misc/misconception-technicalcontrols.md
    - misc/understandingcybersecurityethics.md
    - misc/aibootcamp2025-day1.md
    - misc/aibootcamp2025-day2.md
    - misc/aibootcamp2025-day3.md
    - misc/summerbootcamp2025-day1.md
    - misc/summerbootcamp2025-day2.md
    - misc/summerbootcamp2025-day3.md
  - Out of Band Podcast:
    - podcast/outofband/index.md
    - podcast/outofband/episode0.md
    - podcast/outofband/episode1.md
    - podcast/outofband/episode2.md
    - podcast/outofband/episode3.md    
  - About Me:
    - aboutme.md