# Site
site_name: Anto Porter
site_url: https://antoporter.github.io
site_author: Anthony Porter.
site_description: Welcome to My Cloud Security Hub
edit_uri: edit/main/docs

# Repository
repo_name: AntoPorter
repo_url: https://github.com/AntoPorter/antoporter.github.io

# Themes
theme:
 name: material
 features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
 language: en
 favicon: images/favicon.png
 logo: images/logo.png

# Plugins
 plugins:
  - macros
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - social:
      cards_layout: default
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'


# Colour Schemes
 palette:
  - scheme: slate
    toggle:
     icon: material/toggle-switch-off-outline
     name: Switch to light mode
    primary: teal
    accent: deep purple
  - scheme: default
    toggle:
     icon: material/toggle-switch
     name: Switch to dark mode
    primary: teal
    accent: deep purple

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/AntoPorter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/anthonyantoporter/

  analytics:
    provider: google
    property: G-2H6Z23PMCP

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Copyright
copyright: |
  &copy; 2024 <a href="https://github.com/AntoPorter"  target="_blank" rel="noopener">Anthony Porter</a>

# Navigation
nav:
  - Homepage:
    - index.md
    - Microsoft Defender XDR: defenderxdr/index.md
    - Endpoint Management: endpoint/index.md
    - Microsoft Copilot: copilot/index.md
    - Microsoft Entra: entra/index.md
    - About Me: aboutme.md
  - Microsoft Defender XDR:
    - Microsoft Defender XDR: defenderxdr/index.md
    - Microsoft Defender for Endpoint:
      - defenderxdr/defenderendpoint/enforcementscope.md
    - Microsoft Defender for Office 365:
      - defenderxdr/defenderoffice365/ll-safelinks-rewrap.md
    - Microsoft Defender for Identity:
      - defenderxdr/defenderidentity/top5features.md  
    - Microsoft Defender for Cloud Apps:
      - defenderxdr/defendercloudapps/appblocking-dfe.md
      - defenderxdr/defendercloudapps/unsanctioning-riskyapps.md
    - Microsoft Sentinel:
      - defenderxdr/sentinel/workspaceworkbookexport.md 
  - Endpoint Management: 
    - Endpoint Management: endpoint/index.md
    - Microsoft Intune:
      - endpoint/intune/remediations.md
      - endpoint/intune/bitlocker_selfservice.md
      - endpoint/intune/baselineinsights.md
    - Microsoft Configuration Manager:
      - endpoint/configmgr/challengesolution-mcmtointune.md
  - Microsoft Copilot:
    - Microsoft Copilot: copilot/index.md
    - Microsoft Copilot for Security:
      - copilot/copilotsecurity/deploy-templatespec.md
      - copilot/copilotsecurity/logicapp-promptbook.md
      - copilot/copilotsecurity/promptinspiration.md
      - copilot/copilotsecurity/ll-scudeployment.md
    - Microsoft Copilot for M365:
      - copilot/copilotm365/gettingstarted.md
      - copilot/copilotm365/enablecopilotm365.md
  - Microsoft Entra:
    - entra/index.md
    - entra/azconnect-device.md
  - About Me:
    - aboutme.md